version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${RABBITMQ_MAINPORT}:5672"  # RabbitMQ main port
      - "${RABBITMQ_MANAGMENT}:15672"  # RabbitMQ management interface
    networks:
      - node_network
  bot:
    build: .
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${SESSIONS_PATH}:${SESSIONS_PATH}
      - ${LOGS_PATH}:/code/logs
    working_dir: /code/
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node ./dist/app.js'
    env_file:
      - .env
    restart: on-failure
    networks:
      - node_network
networks:
  node_network:
    driver: bridge
