version: '3'

services:

  bot:
    build: .
    volumes:
      - /var/payload-admin/media:/var/payload-admin/media
    working_dir: /code/
    command: node ./dist/app.js
    env_file:
      - .env