version: '3'

services:

  bot:
    build: .
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${SESSIONS_PATH}:/code/sessions
      - ${LOGS_PATH}:/code/logs
    working_dir: /code/
    command: node ./dist/app.js
    env_file:
      - .env
    restart: on-failure